### PR TITLE
Ability to set start/end date - Surface totalResults in report response

### PR DESCRIPTION
**Pull request by Waseem-Q**
include ability to set start_date and end_date as specified in documentation

openSearch:totalResults is returned by Google to be used for paging.  Currently this field is not surfaced by the garb library and so paging is not usable.

### CODE REVIEW

**Comment by tpitale** [comment]
We don't want to have to re-parse with Crack. I'll take a look at getting the total results.

The start_date/end_date are an error on my part and will be fixed shortly.

**Comment by jmozeika** [comment]
tpitale,

Do you have an ETA on this bug? (start_date, end_date)

I'm trying to figure out whether or not it's worth my time forking and trying to fix it myself.

**Comment by tpitale** [comment]
I've got the total results stuff and I'll get to the start and end dates this weekend.

**Comment by jmozeika** [comment]
Great.  Thanks for the update.

**Comment by tpitale** [comment]
I committed my changes and will push out a gem as soon as I fix these two other bugs.

**Pull request closed without merging**
